import { makeStyles, createStyles } from '@material-ui/styles';
import { Theme } from '@material-ui/core/styles';

export const useStyles = makeStyles((theme: Theme) =>
  createStyles({
    appBar: {
      display: 'flex',
      flexDirection: 'column',
      justifyContent: 'center',
      backgroundColor: '#ffff',
      paddingTop: '10px',
      paddingBottom: '10px',
      border: 'solid 0.5px #E1E3E3',
    },
    navList: {
      display: 'flex',
      marginLeft: 'auto',
      marginRight: '40px',
    },
    navItems: {
      cursor: 'pointer',
      marginRight: '10px',
      fontWeight: 'bold',
      fontSize: '14px',
    },
    navListItem: {
      color: '#1a1c21',
      padding: '8px',
      fontFamily: 'roboto, Arial, sans-serif',
      fontSize: '14px',
      lineHeight: '18px',
      fontWeight: 700,
      '&:hover': {
        backgroundColor: 'black',
        color: 'white',
        borderRadius: '3px',
      },
    },
    discy: {
      color: 'blue',
    },
    home: {
      backgroundColor: 'black',
      color: 'white',
      borderRadius: '3px',
      fontFamily: 'roboto, Arial, sans-serif',
      fontSize: '14px',
      lineHeight: '18px',
      fontWeight: 700,
      paddingLeft: '8px',
      paddingRight: '8px',
      paddingTop: '7px',
    },
    btn1: {
      color: '#707885',
      fontFamily: 'roboto, Arial, sans-serif',
      fontSize: '14px',
      lineHeight: '18px',
      fontWeight: 700,
      display: 'flex',
      alignItems: 'center',
      textTransform: 'none',
      paddingLeft: '5px',
      paddingRight: '6px',
      cursor: 'pointer',
      height: '25px',
      borderRadius: '2px',
      '&:hover': {
        backgroundColor: 'red',
        color: 'white',
      },
    },
    btn2: {
      backgroundColor: 'blue',
      color: 'white',
      fontFamily: 'roboto, Arial, sans-serif',
      fontSize: '14px',
      lineHeight: '18px',
      fontWeight: 700,
      display: 'flex',
      alignItems: 'center',
      textTransform: 'none',
      paddingLeft: '5px',
      paddingRight: '6px',
      marginRight: '10px',
      marginLeft: '10px',
      height: '25px',
      cursor: 'pointer',
      borderRadius: '2px',
      '&:hover': {
        backgroundColor: 'black',
      },
    },
    searchAppbar: {
      backgroundColor: '#f5f5f5',
      fontSize: '12px',
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'space-around',
      width: '200px',
      marginLeft: '5px',
      marginRight: '12px',
      height: 'fit-content',
    },
    searchText: {
      fontFamily: 'open sans, Arial, sans-serif',
      fontSize: '12px',
      fontWeight: 400,
      color: '#7c7f85',
      fontStyle: 'italic',
      marginLeft: '0',
    },
    searchIcon: {
      color: '#7c7f85',
      fontFamily: 'entypo',
      fontSize: '19px',
      fontWeight: 400,
      marginRight: '0',
      cursor: 'pointer',
    },
  }),
);
